config/routes.rb
Rails.application.routes.draw do
  resources :information
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:name, :idnum, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_with(model: information, local: true) do |form| %>
  <% if information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :information_name %>
  </div>

  <div class="field">
    <%= form.label :idnum %>
    <%= form.number_field :idnum, id: :information_idnum %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :information_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :information_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/information/edit.html.erb
<h1>Editing Information</h1>

<%= render 'form', information: @information %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

app/views/information/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Information</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Idnum</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
      <tr>
        <td><%= information.name %></td>
        <td><%= information.idnum %></td>
        <td><%= information.phone %></td>
        <td><%= information.email %></td>
        <td><%= link_to 'Show', information %></td>
        <td><%= link_to 'Edit', edit_information_path(information) %></td>
        <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Information', new_information_path %>

app/views/information/new.html.erb
<h1>New Information</h1>

<%= render 'form', information: @information %>

<%= link_to 'Back', information_index_path %>

app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @information.name %>
</p>

<p>
  <strong>Idnum:</strong>
  <%= @information.idnum %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @information.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @information.email %>
</p>

<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>